tasks:
  - name: Pull Images
    init: ./services create

ports:
  - name: JSON-LD context (HTTPD)
    description: Public User JSON-LD context
    port: 3004
    onOpen: notify
    visibility: public
  - name: Orion
    description: Context Broker
    port: 1026
    onOpen: notify
    visibility: public
  - name: Scorpio
    description: Context Broker
    port: 9090
    onOpen: notify
    visibility: public
  - name: Stellio
    description: Context Broker
    port: 8080
    onOpen: notify
    visibility: public
  - name: MongoDB
    description: Database for Orion
    port: 27017
    onOpen: ignore