tasks:
  - name: Pull Images
    init: ./services create

ports:
  - name: JSON-LD context (HTTPD)
    description: Public User JSON-LD context
    port: 3004
    onOpen: notify
    visibility: public
  - name: Context Broker
    description: Context Broker
    port: 1026
    onOpen: notify
    visibility: public
  - name: MongoDB
    description: Database for Orion
    port: 27017
    onOpen: ignore
  - name: zookeeper
    description: Synchronization service
    port: 2181
    onOpen: ignore
  - name: kafka
    description: Stream-processing platform
    port: 9092
    onOpen: ignore
  - name: postgres
    description: Database for Scorpio or Stellio
    port: 5432
    onOpen: ignore